# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0-browsers
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: calidad

    steps:
      - checkout

      - restore_cache:
          keys:
            - maven-repo-{{ checksum "pom.xml" }}

      - run:
          name: Install MySQL Client
          command: sudo apt-get update && sudo apt-get install -y mysql-client

      - run:
          name: Wait for MySQL
          command: sleep 50

      - run:
          name: Create database schema
          command: |
            mysql -h 127.0.0.1 -u root -p123456 calidad < src/resources/schema.sql

      - run:
          name: Run Test
          command: mvn test

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target

      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-{{ checksum "pom.xml" }}

workflows:
  sample:
    jobs:
      - build-and-test
