version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0-browsers
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: calidad
          MYSQL_ROOT_PASSWORD: 123456

    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-{{ checksum "pom.xml" }}

      - run:
          name: Install MySQL Client
          command: sudo apt-get update && sudo apt-get install -y mysql-client

      - run:
          name: Wait for MySQL
          command: |
            for i in {1..10}; do
              if mysqladmin ping -h 127.0.0.1 -u root -p123456 --silent; then
                break
              fi
              echo "Waiting for MySQL..."
              sleep 5
            done

      - run:
          name: Create database schema
          command: |
            mysql -h 127.0.0.1 -u root -p123456 -e "CREATE DATABASE IF NOT EXISTS calidad;"
            mysql -h 127.0.0.1 -u root -p123456 -e "USE calidad; CREATE TABLE IF NOT EXISTS usuarios2024 (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            name varchar(15),
            email varchar (50),
            password varchar (16)
            );"

      - run:
          name: Build without tests
          command: mvn -B -DskipTests clean package

      - run:
          name: Run Test
          command: mvn test -Dtest=UserServiceIntegrationTest

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: src/screenshots

      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-{{ checksum "pom.xml" }}

workflows:
  sample:
    jobs:
      - build-and-test
